AccessDeniedError [SequelizeAccessDeniedError]: Access denied for user ''@'localhost' (using password: YES)
    at ConnectionManager.connect (C:\nodejs\server\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:94:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (C:\nodejs\server\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:222:24)
    at async C:\nodejs\server\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\nodejs\server\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\nodejs\server\node_modules\sequelize\lib\sequelize.js:305:26
    at async MySQLQueryInterface.tableExists (C:\nodejs\server\node_modules\sequelize\lib\dialects\abstract\query-interface.js:102:17)
    at async role.sync (C:\nodejs\server\node_modules\sequelize\lib\model.js:939:21)
    at async Sequelize.sync (C:\nodejs\server\node_modules\sequelize\lib\sequelize.js:377:9) {
  parent: Error: Access denied for user ''@'localhost' (using password: YES)
      at Packet.asError (C:\nodejs\server\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\nodejs\server\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\nodejs\server\node_modules\mysql2\lib\connection.js:490:32)
      at PacketParser.onPacket (C:\nodejs\server\node_modules\mysql2\lib\connection.js:95:12)
      at PacketParser.executeStart (C:\nodejs\server\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\nodejs\server\node_modules\mysql2\lib\connection.js:102:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user ''@'localhost' (using password: YES)",
    sql: undefined
  },
  original: Error: Access denied for user ''@'localhost' (using password: YES)
      at Packet.asError (C:\nodejs\server\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\nodejs\server\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\nodejs\server\node_modules\mysql2\lib\connection.js:490:32)
      at PacketParser.onPacket (C:\nodejs\server\node_modules\mysql2\lib\connection.js:95:12)
      at PacketParser.executeStart (C:\nodejs\server\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\nodejs\server\node_modules\mysql2\lib\connection.js:102:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user ''@'localhost' (using password: YES)",
    sql: undefined
  }
}
